"""
This script takes an existing Hugging Face model and fine-tunes it to differentiate between injection attacks
and benign inputs.
It will show prediction accuracy before and after fine-tuning the model to show that the fine-tuning was effective
for the purpose of differentiating between the two different types of inputs.
A lot of guidance for this code came from https://ranjankumar.in/llm-powered-chatbots-a-practical-guide-to-user-input-classification-and-intent-handling
"""
import pandas as pd
import numpy as np

from pathlib import Path
from datasets import Dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from transformers import (AutoTokenizer,AutoModelForSequenceClassification,TrainingArguments,Trainer, pipeline)

# Set project paths
BASE_DIR = Path(__file__).resolve().parent
prompts = BASE_DIR / "docs" / "prompts.csv"
save_folder = BASE_DIR / "model" / "chat_classifier"

# Load CSV. CSV file contents were generated by ChatGPT (https://chatgpt.com/share/69fa0870-bf64-8327-993b-a321f300a91b)
df = pd.read_csv(prompts)

# Convert labels to numbers
label_map = {
    "benign": 0,
    "attack": 1
}

id_to_label = {
    0: "benign",
    1: "attack"
}

df["label"] = df["label"].map(label_map)

# Split into train/test sets
# Rather than making a csv splitter as we did earlier in the class, I utilized train_test_split (https://www.geeksforgeeks.org/machine-learning/how-to-do-train-test-split-using-sklearn-in-python/)
train_df, test_df = train_test_split(
    df,
    test_size=0.2,
    random_state=42,
    stratify=df["label"]
)
# The HuggingFace model uses more labels than "benign" and "attack" so we have to remap them
def label_to_number(pred_label):
    pred_label = pred_label.lower()

    if pred_label in ["attack", "injection", "malicious", "unsafe", "label_1"]:
        return 1

    if pred_label in ["benign", "safe", "clean", "label_0"]:
        return 0

    # If label is not recognized, send this alert
    print("Label not recognized:", pred_label)
    return 0


# Evaluate the HuggingFace model on our test data before fine-tuning so that we can compare results
def evaluate_model(model_path, tokenizer_path, test_df, title):
    clf = pipeline(
        "text-classification",
        model=model_path,
        tokenizer=tokenizer_path,
        truncation=True,
        max_length=128
    )

    correct = 0
    total = len(test_df)

    for _, row in test_df.iterrows():
        text = row["prompt"]
        true_label = row["label"]

        result = clf(text)[0]
        pred_label = label_to_number(result["label"])

        if pred_label == true_label:
            correct += 1

    accuracy = correct / total
    return accuracy

# Hugging Face model
MODEL = "protectai/deberta-v3-base-prompt-injection-v2"

# Test model results before fine-tuning
before_acc = evaluate_model(
    MODEL,
    MODEL,
    test_df,
    "Before Fine-Tuning Accuracy:"
)


#Dataset conversion source: https://www.codestudy.net/blog/how-do-i-convert-pandas-dataframe-to-a-huggingface-dataset-object/
train_dataset = Dataset.from_pandas(train_df)
test_dataset = Dataset.from_pandas(test_df)

tokenizer = AutoTokenizer.from_pretrained(MODEL)

def tokenize(batch):
    return tokenizer(
        batch["prompt"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

train_dataset = train_dataset.map(tokenize, batched=True)
test_dataset = test_dataset.map(tokenize, batched=True)

# Remove columns that the model does not need
columns_to_remove = ["prompt"]

# This is a column added by Dataset.from_pandas that we do not need
if "__index_level_0__" in train_dataset.column_names:
    columns_to_remove.append("__index_level_0__")

train_dataset = train_dataset.remove_columns(columns_to_remove)
test_dataset = test_dataset.remove_columns(columns_to_remove)

# Make the dataset compatible with the model with PyTorch
train_dataset.set_format("torch")
test_dataset.set_format("torch")

# Load model
model = AutoModelForSequenceClassification.from_pretrained(
    MODEL,
    num_labels=2,
    id2label=id_to_label,
    label2id=label_map
)

# Compute accuracy
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)

    accuracy = accuracy_score(labels, predictions)

    return {
        "accuracy": accuracy,
    }

training_args = TrainingArguments(
    output_dir=str(BASE_DIR / "results"),
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=4,
    weight_decay=0.01,
    logging_dir=str(BASE_DIR / "logs"),
    load_best_model_at_end=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

# Fine-tune model
trainer.train()

# Evaluate model
results = trainer.evaluate()
print("\nEvaluation results:")
print(results)

# Save fine-tuned model
trainer.save_model(str(save_folder))
tokenizer.save_pretrained(str(save_folder))

print("Model saved successfully")

after_acc = evaluate_model(
    str(save_folder),
    str(save_folder),
    test_df,
    "After Fine-Tuning"
)

print("\nFinal Comparison:")
print(f"Before Fine-Tuning Accuracy: {before_acc:.4f}")
print(f"After  Fine-Tuning Accuracy: {after_acc:.4f}")